name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_calendar: yes
          plugin_calendar_limit: 1 > 0
          plugin_languages: yes
          plugin_languages_indepth: yes
          commits_authoring: sueder morais, dreuse, dreuse@users.noreply.github.com, smorais
          plugin_languages_colors: rainbow
